### ISSUE TITLE
Solr findet solrconfig.xml nicht

### ISSUE THREAD

**Issue by caffeineFox** [saschaszott/opus4-docker#3]
Folgende Fehlermeldung zeigt sich nach dem Start auf der Solr-Adminseite: `Could not load conf for core opus4: Error loading solr config from opt/solr/server/solr/mycores/opus4/conf/solrconfig.xml`
Ich vermute, das liegt daran, dass der Ordner `conf` komplett fehlt.
`mkdir`, Dateien reinkopieren, Zugriffsrechte, `chown` auf solr, dann Container neustarten hat nichts gebracht. Habe das alles mit dem Stand des Master-Branches von OPUS4 ausprobiert.

Das gleiche Problem trat schon einmal auf, als ich mich an die Installationsanleitung von OPUS4 gehalten habe und das alles auf einen Ubuntu-Container installieren wollte. Auch da hat solr die `solrconfig` par tout nicht gefunden, obwohl sie sowohl im Ordner des Core als auch in dessen `conf`-Unterordner lag.

**Comment by saschaszott** [comment]
Oh, habe das Ticket erst jetzt gesehen. Danke für das Feedback. Wir sind auch schon gegen diese Problem gerannt, weil Solr den Verzeichnisnamen `conf` erwartet, aber in OPUS4 das Verzeichnis `config` heißt. Ein Symlink im Solr-Docker-Container hilft als schneller Workaround. 

Es gibt aber keinen Grund, warum OPUS4 nicht auch `conf` als Verzeichnisnamen wählen kann. Daher soll das Verzeichnis umbenannt werden (in https://github.com/OPUS4/opus4-search). Ich hatte dazu schon mit Jens Schwidder vom KOBV (OPUS4 Main Developer) Kontakt und er war einverstanden, dass wir diese Änderung machen können.

Das Problem löst sich mit der Erledigung von PR https://github.com/OPUS4/application/pull/207 (siehe dort den vorletzten Kommentar von @j3nsch). Bis dahin einfach mit Symlink arbeiten ;)

**Comment by saschaszott** [comment]
Der für das Problem zuständige PR lautet OPUS4/application#271. Der wurde mittlerweile gelöst, so dass mit dem nächsten OPUS4-Release (4.7) das Problem beseitigt ist.

**Comment by saschaszott** [comment]
@caffeineFox ich habe die Solr-Konfiguration im `docker-compose.yml` nochmal angepasst. Der Solr-Core `opus4` wird nun nicht mehr im Unterverzeichnis `mycores` angelegt. Außerdem kann nun auf den Symlink von `config` auf `conf` verzichtet werden. Ein Zusatzschritt ist allerdings erforderlich: im Core-Verzeichnis muss eine leere Datei mit dem Namen `core.properties` angelegt werden.

**Comment by caffeineFox** [comment]
Hi @saschaszott danke für die Mühen, bitte entschuldige, dass ich nicht mehr reagiert habe! Werde es demnächst ausprobieren :)

**Comment by saschaszott** [comment]
über Feedback würde ich freuen ;)
